### PR TITLE
Flags

### PR DESCRIPTION
**Pull request by bennyman123abc**

### CODE REVIEW

**Comment by Brawl345** [comment]
You need to add the flag to this array or else it won't be shown in the frontend: https://github.com/WiiDatabase/RiiTag-Next/blob/master/src/lib/constants/forms/flags.js#L1

**Comment by Brawl345** [comment]
Please just add a new commit to your `flags` branch. It will automatically update this PR, no need to create a new one.

**Comment by bennyman123abc** [comment]
Sorry for the late reply; need to check Github notifs more often lol. I don't see a flags branch on this repo. Has it been removed since this PR?

**Comment by bennyman123abc** [comment]
Sorry, I realized what you meant now. The flags branch on my repo

**Comment by bennyman123abc** [comment]
Updated flags.js

**Pull request merged**
